### ISSUE TITLE
Out of memory on standard Mac Docker installation

### ISSUE THREAD

**Issue by Spark3000** [richardgill/tailwind-override#21]
Hey guys. 

FANTASTIC package. Just wanted to let you know that first. 
(There definitely should be a Github place for "Giving Mad Props", but issues will have to do) 

This package should be an official Tailwind thing.  Also looking forward to JIT dynamic class compatibility. 

That said I haven't got it working yet on a Docker Next JS  installation as I get a JS heap allocation error. I've tried increasing general memory and disk available to Docker but it didn't work. I'm guessing parsing the big JSON is pretty memory intensive. 

I'm going to keep troubleshooting this tonight but was wondering in the meantime if you had a solve before I do.

Thanks!

**Comment by jagaa999** [comment]
Me too. Also memory error. Sad!

**Comment by richardgill** [comment]
@Spark3000 @jagaa999 

This is definitely a problem and I currently don't have a good solution. This package loads a very large json file which as you say is likely the cause here.

If there is enough interest I'm thinking of rewriting the package to work in a different way to support the new tailwind JIT feature that fixes both in one shot. I'm a little bit unsure on how to do that in a way that's robust - but I'm thinking about it!

**Comment by richardgill** [comment]
@Spark3000 @jagaa999 

tailwind-override 0.5.0 is 32KB, and no longer involves loading in a massive json file - so you should be good to go 👍 

https://www.npmjs.com/package/tailwind-override

**Comment by Spark3000** [comment]
😳 
Nice! Will check

**Comment by jagaa999** [comment]
Woow, Thank you!
