### ISSUE TITLE
Inefficient / Slow Render Updating

### ISSUE THREAD

**Issue by aakagi** [richardgill/tailwind-override#26]
Hi, thank you for this project, it's super useful!

I've found myself wanting to use `tailwind-override` every time I use the `classnames` package, so I made a small utility function `cxo` that wraps `classnames` with `overrideTailwindClasses`.

This works well, but can't be used indiscriminately because it causes render times to increase significantly for components that are rendered many times as items in a list.

The work-around is to simply not use the package if a component is rendered a bunch of times, but I was wondering if anyone has ideas for how we might be able to modify the package to make `isTailwindClash` more efficient.

I've attached two screenshots of the Chrome performance tab below, to show the difference between using my modified `cxo` class which uses `overrideTailwindClasses`, and just using regular `cx` from `classnames`.

The difference in updateFunctionComponent is **900.8ms** vs **6.2ms**.

It appears this is caused downstream, in large part, by `getRules` called by `findTailwindProperties` called by `isTailwindClash`.

I think this package is super useful so I'll be happy to help out if anyone has any ideas for what would work!

### 1: With overrideTailwindClasses: updateFunctionComponent's total time takes 900.8ms
<img width="1440" alt="Screen Shot 2021-11-17 at 11 49 58 AM" src="https://user-images.githubusercontent.com/7625040/142273740-288730f4-d48d-4f0e-a405-716df8a565ed.png">

### 2. Without overrideTailwindClasses (classnames only): updateFunctionComponent's total time takes 6.2ms 
<img width="1440" alt="Screen Shot 2021-11-17 at 11 54 09 AM" src="https://user-images.githubusercontent.com/7625040/142273756-c3180bd5-5f1f-48b9-ae9c-615220142a23.png">

**Comment by richardgill** [comment]
Hi @aakagi thanks all the details!

I've just released 0.6.0 which should improve things. It takes the slowest part of the code and memoizes it - this means the second time you mention a class e.g. `bg-gray-500` it won't need to do the lookup again. 

For the usecase you describe this will likely help a lot, since you're probably passing in the same classes over and over again as your component renders. 

This library will likely never be as fast as `classNames(` because it has to do more calculations to figure out which tailwind classe clash - but hopefully this improves things enough for you.

[bg-gray-500](https://github.com/richardgill/tailwind-override/pull/27)
